# Generated by Django 5.2 on 2025-04-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritething',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='favorite_things/'),
        ),
    ]
